### ISSUE TITLE
Killing with a MicroHID says killed with a tesla gate.

### ISSUE THREAD

**Issue by Jetmax937** [ServerMod/SCPDiscord#103]
Example:

Jetmax937 (76561198101200007) was killed by Dahlias (76561198164387989) using a tesla gate.

MTF Dahlias (76561198164387989) was teamkilled by MTF Jetmax937 (76561198101200007) using a tesla gate.

**Comment by KarlOfDuty** [comment]
Fixed. fc4fb757c4d68d2b13aa1230406892b83b6cf798
