### ISSUE TITLE
Teamkilling using grenades dont show as teamkills.

### ISSUE THREAD

**Issue by Jetmax937** [ServerMod/SCPDiscord#104]
Matri threw a grenade in an elevator being MTF, killing the rest of MTF on a friendly fire server.

Matri El InBaniable (76561198152232374) threw a grenade.
Matri El InBaniable (76561198152232374) died by grenade.
TRM22 (76561198134813175) was killed by Matri El InBaniable (76561198152232374) using grenade.
julianBF433 (76561198862885265) was killed by Matri El InBaniable (76561198152232374) using grenade.
Shivano (76561198090555567) was killed by Matri El InBaniable (76561198152232374) using grenade.
La Papa Agresiva (76561198087292987) was killed by Matri El InBaniable (76561198152232374) using grenade.
Sr. Pichón (76561198102548826) was killed by Matri El InBaniable (76561198152232374) using grenade.

**Comment by KarlOfDuty** [comment]
Caused by the one throwing the grenade dying before the rest.

**Comment by KarlOfDuty** [comment]
I will likely not fix this as it would create unnecessary overhead for a very small issue.
