### ISSUE TITLE
Suggestion: multi-server instances support for single node

### ISSUE THREAD

**Issue by REALMWTH** [ServerMod/SCPDiscord#107]
Title

**Comment by KarlOfDuty** [comment]
Does this mean multiple discord servers or multiple scp:sl servers?

**Comment by KarlOfDuty** [comment]
@realmbmc

**Comment by REALMWTH** [comment]
No, multiple server instances connecting to single NodeJS bot.

**Comment by REALMWTH** [comment]
To report to single Discord server but different text channels

**Comment by KarlOfDuty** [comment]
I see, that should already be possible.
