### ISSUE TITLE
Make config option to disable server console "sent message" [Suggestions]

### ISSUE THREAD

**Issue by SpaceMau5e** [ServerMod/SCPDiscord#12]
My server keeps running low on memory due to the server console filling with the "sent message ... to discord". Other than that this is proving to be helpful and like by my server's community. But would it be possible to add a config option to disable "sent message ... to discord" from server console or at least have it send fewer messages through the server console?

**Comment by KarlOfDuty** [comment]
Hm... Are you sure that is the issue? Simple console messages shouldn't really increase ram usage by any noticeable amount as far as I know.

**Comment by KarlOfDuty** [comment]
Done #30
