### ISSUE TITLE
timestamp: "" seems not working

### ISSUE THREAD

**Issue by Barna13** [ServerMod/SCPDiscord#125]
Hi,
When I set on the config timestamp: "", on the channel discord he write me [12/05/2018 17:36:06]:xxxx
Thanks.

**Comment by KarlOfDuty** [comment]
Are you sure you are using the right config? And have you restarted the server or reloaded the plugin?

**Comment by Barna13** [comment]
Yes i have make a +scpd_reload and a restart server

**Comment by KarlOfDuty** [comment]
Yes, I just tested it, I'll make a fix soon.

**Comment by Barna13** [comment]
Nice thank you

**Comment by KarlOfDuty** [comment]
Oh yeah, it's actually supposed to be "off" to turn it off. I've fixed it now.
