### ISSUE TITLE
start.sh has \r\n line endings, cannot run on Linux without dos2unix

### ISSUE THREAD

**Issue by PatPeter** [ServerMod/SCPDiscord#131]
I have to convert the start.sh file whenever I update SCPDiscord from \r\n to \n line endings.

**Comment by KarlOfDuty** [comment]
Pretty sure that's just github playing around with the file endings, not sure if I can change that.

**Comment by KarlOfDuty** [comment]
I've removed the start scripts so this issue doesn't matter anymore
