### ISSUE TITLE
Log constantly spits out Checking if round has ended... when a game is going and I can't figure out how to disable it

### ISSUE THREAD

**Issue by kou4ben3** [ServerMod/SCPDiscord#132]
I have two logs set up and it only seems to happen on the second one (extra-detailed). I can't seem to find which of the options would affect this or how to turn it off.
Configuration:

    `statusmessages: [ "in-game-log", "extra-detailed-log"]

    # Channel topic updater
    topic: [ "in-game-log", "extra-detailed-log"]

    # Round events
    onroundstart: [ "in-game-log", "extra-detailed-log"]
    onconnect: ["in-game-log", "extra-detailed-log"]
    ondisconnect: ["in-game-log","extra-detailed-log"]
    oncheckroundend: ["extra-detailed-log"]
    onroundend: [ "in-game-log", "extra-detailed-log"]
    onwaitingforplayers: [ "in-game-log", "extra-detailed-log" ]
    onroundrestart: [ "in-game-log", "extra-detailed-log"]
    onsetservername: []
    onscenechanged: []

    # Environment events
    onscp914activate: ["extra-detailed-log"]
    onstartcountdown: 
        initiated: [ "in-game-log", "extra-detailed-log" ]
        resumed: [ "in-game-log", "extra-detailed-log" ]
    onstopcountdown: [ "in-game-log", "extra-detailed-log" ]
    ondetonate: [ "in-game-log", "extra-detailed-log" ]
    ondecontaminate: [ "in-game-log", "extra-detailed-log" ]
    
    # Player events
    onplayerhurt:
        default: ["extra-detailed-log"]
        friendlyfire: ["extra-detailed-log"]
        noattacker: ["extra-detailed-log"]
    onplayerdie: 
        default: ["in-game-log","extra-detailed-log" ]
        friendlyfire: ["teamkill-log", "extra-detailed-log" ]
        noattacker: ["in-game-log","extra-detailed-log" ]
    onplayerpickupitem: ["extra-detailed-log"]
    onplayerdropitem: ["extra-detailed-log"]
    onplayerjoin: [ "in-game-log", "extra-detailed-log" ]
    onnicknameset: []
    onassignteam: ["extra-detailed-log"]
    onsetrole: ["extra-detailed-log"]
    oncheckescape:
        allowed: ["extra-detailed-log" ]
        denied: []
    onspawn: [ "extra-detailed-log" ]
    ondooraccess:
        allowed: ["extra-detailed-log"]
        denied: ["extra-detailed-log"]
    onintercom: ["in-game-log","extra-detailed-log"]
    onintercomcooldowncheck: []
    onpocketdimensionexit: [ "extra-detailed-log" ]
    onpocketdimensionenter: [ "extra-detailed-log" ]
    onpocketdimensiondie: ["extra-detailed-log"]
    onthrowgrenade: ["extra-detailed-log" ]
    onplayerinfected: ["extra-detailed-log" ]
    onspawnragdoll: []
    onlure: []
    oncontain106: ["in-game-log","extra-detailed-log" ]
    onmedkituse: [ "extra-detailed-log" ]
    onshoot:
        default: ["extra-detailed-log"]
        friendlyfire: ["extra-detailed-log"]
        notarget: []
    on106createportal: ["extra-detailed-log"]
    on106teleport: ["extra-detailed-log"]
    onelevatoruse: ["extra-detailed-log"]
    onhandcuff:
        default: [ "extra-detailed-log" ]
        nootherplayer: []
    onplayertriggertesla:
        default: ["extra-detailed-log"]
        ignore: []
    onscp914changeknob: []
    
    # Admin events
    onadminquery: [ "extra-detailed-log" ]
    onauthcheck: []
    onban: 
        admin: [ "in-game-log", "server-ban-log", "extra-detailed-log" ]
        console: [ "in-game-log", "server-ban-log", "extra-detailed-log" ]

    # Team events
    ondecideteamrespawnqueue: []
    onsetrolemaxhp: []
    onteamrespawn:
        mtf: ["in-game-log", "extra-detailed-log"]
        ci: [ "in-game-log", "extra-detailed-log" ]
    onsetscpconfig: []
    onsetntfunitname: [ "in-game-log", "extra-detailed-log" ]`

**Comment by KarlOfDuty** [comment]
![image](https://user-images.githubusercontent.com/18099825/50767444-2ad00a80-127d-11e9-84f6-89d31c98b3af.png)
