### ISSUE TITLE
Hide(or describe) postround teamkills

### ISSUE THREAD

**Issue by 017** [ServerMod/SCPDiscord#142]
It would be useful to have the bot's logs ID if a teamkill occurs in the postround versus during the active round, so someone who is reading the logs (but not ingame) can tell if it's actual legitimate teamkills and not just post-round deathmatching in the last moments.

**Comment by KarlOfDuty** [comment]
I mean you can just check if it happens after the round has ended?

**Comment by KarlOfDuty** [comment]
Done. 5b27c2c7766cbf49eb128c802f9ba0e42a51ae5a
