### ISSUE TITLE
Bot Maker?

### ISSUE THREAD

**Issue by Luke-san** [ServerMod/SCPDiscord#143]
I was wondering if there was a program similar to this that would be compatible with discord bot maker?

**Comment by KarlOfDuty** [comment]
I have no idea what that is.

**Comment by Luke-san** [comment]
Discord Bot Maker is a program on steam that is used to create custom discord bots. The program is fully modifiable and is easy to use. You should probably make this a mod for it fam.

**Comment by KarlOfDuty** [comment]
Pretty sure that is not possible, just looks like a random code generator.
