### ISSUE TITLE
Getting IP of connection player event

### ISSUE THREAD

**Issue by REALMWTH** [ServerMod/SCPDiscord#16]
Player is trying to connect...
But now with IP address

**Comment by KarlOfDuty** [comment]
I think showing everyone's ip publicly would be bad. But in the future I could add a discord command that get's the ip of a player.

**Comment by KarlOfDuty** [comment]
I won't implement this as it would easily lead to exposing user IP-addresses publically.

**Comment by KarlOfDuty** [comment]
This will be possible with the new messages system.

**Comment by KarlOfDuty** [comment]
Done. #36
