### ISSUE TITLE
Bug? MultiAdmin SCPDiscord doesn't use global configs nor global role sync on sub servers

### ISSUE THREAD

**Issue by eDexiam** [ServerMod/SCPDiscord#163]
So when using Multi admin with multiple servers it creates it's config files in the sub server directory however the wiki says that it's using the global config which it is not. Attempts to delete the SCP discord folders have lead to it recreating the folders on both sub servers. This leads to issues as my role sync only works on one server.

**Comment by KarlOfDuty** [comment]
The new multiadmin moves the config folder for all plugins to the local one, it is not an scpdiscord issue. The next version will have config options to use either the local or global location.

**Comment by eDexiam** [comment]
I don't want to sound too impatient but do you have an ETA on the next release? People have already started complaining that they don't have their rank on both servers (Especially my staff) :|

**Comment by KarlOfDuty** [comment]
just have them use the rolesync command on both servers?

**Comment by eDexiam** [comment]
Well I found a temporary solution is to automatically copy the main role sync file to the other server however it doesn't reload the file until a server restart so that will have to do in the meantime

**Comment by KarlOfDuty** [comment]
*but why not just run the syncrole command on both servers*

**Comment by eDexiam** [comment]
_Because people find it stupid to do so_ ._.

**Comment by KarlOfDuty** [comment]
Done. 57b25e7ec13e461b73cc596e9cdf2a120f31a25b
