### ISSUE TITLE
Rolesync gives permissions to the server but not badge

### ISSUE THREAD

**Issue by Kei-Shin** [ServerMod/SCPDiscord#168]
The player can sync the roles and I see the server log saying the rank is being assigned to them and permissions are issued to them but you cannot see that the rank was applied in the "N" menu.

**Comment by KarlOfDuty** [comment]
It's a bug in the last version, it's already fixed in the upcoming one.
[SCPDiscord.zip](https://github.com/KarlOfDuty/SCPDiscord/files/3066410/SCPDiscord.zip)
