### ISSUE TITLE
Intercom usage causes massive log spam

### ISSUE THREAD

**Issue by REALMWTH** [ServerMod/SCPDiscord#17]

**Comment by KarlOfDuty** [comment]
Is this only with a specific config option on?

**Comment by KarlOfDuty** [comment]
Because some config options are not meant to be used other than for testing as they activate all the time.

**Comment by REALMWTH** [comment]
Both of intercom configs are causing log spam

**Comment by KarlOfDuty** [comment]
Right, that is probably the expected outcome then. They are probably not useful for this plugin in that case.

**Comment by KarlOfDuty** [comment]
This event is supposed to trigger at this frequency.
