### ISSUE TITLE
How to run bot (and more)

### ISSUE THREAD

**Issue by ClTYOFEVlL** [ServerMod/SCPDiscord#180]
This sounds stupid but the bot file just has a .js file and it doesn't run. Also, what if I have an FTB connected server? I just really want to make sure my "Admins" are really being admins.
I'm not the best at stuff and I don't even know how to put the bot into a sever sorry
(used the wiki already not helping)

**Comment by KarlOfDuty** [comment]
It's right here in the last page of the setup guide:
![image](https://user-images.githubusercontent.com/18099825/57814397-d4676100-7773-11e9-8fbb-cee21b5065aa.png)

Also please explain what you mean by an FTB connected server? And also what you mean by making sure your admins are really being admins?

**Comment by ClTYOFEVlL** [comment]
Sorry I had went to bed after I sent that. I mean my server is hosted on ZAP and I'm unsure if it will still work. What I mean by making sure my admins are being admins are like seeing if they are admin abusing and this I'm pretty sure has that feature. Otherwise I'm stuck on this screen. 
![image](https://user-images.githubusercontent.com/25782134/57883623-c60d5980-77f4-11e9-9b03-1f7299ad78b7.png)

**Comment by KarlOfDuty** [comment]
Ah I see, I have no idea if that will work, ZAP servers are not supported.

You can set what messages you want the plugin to send in the plugin config, you can set an admin log channel up there.

**Comment by ClTYOFEVlL** [comment]
Ok.
