### ISSUE TITLE
Error when running bot

### ISSUE THREAD

**Issue by danya201272** [ServerMod/SCPDiscord#191]
/home/server/.pm2/logs/SCPDiscordBot-error.log last 15 lines:
0|SCPDisco |      type: 'MAP',
0|SCPDisco |      value: null,
0|SCPDisco |      items:
0|SCPDisco |       [ [QuoteDouble],
0|SCPDisco |         [CollectionItem],
0|SCPDisco |         [QuoteDouble],
0|SCPDisco |         [CollectionItem],
0|SCPDisco |         [QuoteDouble],
0|SCPDisco |         [CollectionItem] ],
0|SCPDisco |      resolved:
0|SCPDisco |       YAMLMap {
0|SCPDisco |         items: [Array],
0|SCPDisco |         tag: 'tag:yaml.org,2002:map',
0|SCPDisco |         range: [Array],
0|SCPDisco |         type: 'MAP' } } }

**Comment by KarlOfDuty** [comment]
Please run it normally using node, it will have more info. The issue is likely from you not having updated your config. Check the guide for the current one.

**Comment by KarlOfDuty** [comment]
Is this still an issue?
