### ISSUE TITLE
Specify version removal of scpdiscord_config in Config Introduction

### ISSUE THREAD

**Issue by PatPeter** [ServerMod/SCPDiscord#195]
To prevent anyone else from having my same issue, could there be a notice in [Config Introduction](https://github.com/KarlOfDuty/SCPDiscord/wiki/Config-introduction) that scpdiscord_config was removed and in what version?

**Comment by KarlOfDuty** [comment]
Done.

**Comment by PatPeter** [comment]
Thank you!
