### ISSUE TITLE
[BUG] Connecting to bot outside of the server

### ISSUE THREAD

**Issue by IcedHost** [ServerMod/SCPDiscord#199]
**Describe the bug**
The SCPDiscord.dll in sm_plugins doesn't download the SCPDiscord folder like it should.
I am trying to connect to a bot outside of the server file, as I am running my server in a docker (shared host). In the regular SCPDiscord folder on Github you can connect the bot with an IP and port, but that folder isn't being made.

**To Reproduce**
*Check describe bug*

**Screenshots**
Console: https://ibb.co/W5wC3dk
Config (That should be downloaded by .dll): https://ibb.co/GFqSK9K

** Setup (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: Latest
 - Smod Version:  Smod2
 - MultiAdmin version: Latest

**Comment by KarlOfDuty** [comment]
Please post the console output from server startup.

**Comment by IcedHost** [comment]
Thank you for your fast reply.

The only console output I am getting is the one in the screenshot section (https://ibb.co/W5wC3dk)

**Comment by KarlOfDuty** [comment]
Do you have the dependencies? Still, please post all console output from the server startup.

**Comment by IcedHost** [comment]
Dependencies: https://ibb.co/7YzMHtR
Full console output: https://pastebin.com/B4i7ctNv

**Comment by KarlOfDuty** [comment]
This plugin here is broken
![image](https://user-images.githubusercontent.com/18099825/58863656-8cbd6080-86b3-11e9-8e2a-06f7458290f3.png)

**Comment by IcedHost** [comment]
Thanks a lot, works now!

**Comment by KarlOfDuty** [comment]
Nice, np
