### ISSUE TITLE
[BUG] does not send homicide messages from an ally grenade

### ISSUE THREAD

**Issue by agent188** [ServerMod/SCPDiscord#202]
**Describe the bug**
If a lieutenant throws a grenade into an elevator and kills his own, then there are no reports of a grenade killing

**To Reproduce**
1. People enter the elevator
2. We throw a grenade
3. Allies die
4. No messages

**Setup (please complete the following information):**
 - OS: Win10
 - Version: 1.3.1 PRE
 - Smod Version: 3.5.0
 - MultiAdmin version: 3.2.0

**Comment by KarlOfDuty** [comment]
Please post your plugin config.

**Comment by KarlOfDuty** [comment]
Closed due to inactivity.
