### ISSUE TITLE
[BUG] Config [scpdiscord_config_global] doesn't change the config path

### ISSUE THREAD

**Issue by Cyanox62** [ServerMod/SCPDiscord#204]
**Describe the bug**
Regardless of the config `scpdiscord_config_global` being true of false, the plugin uses the global config directory. I looked in the code to see that this config was only used in `FileManager.GetAppFolder(scpdiscord_config_global)`, so I made a test plugin with that parameter set to both true and false. Both lines gave me the same file path, as shown in the attached screenshots. This leads me to believe the config option is getting changed, but the change doesn't seen to affect what file path is gotten. The issue is apparent on both my Arch Linux server and my Windows 10 PC.

**Screenshots**
![1](https://user-images.githubusercontent.com/18158351/61587500-60717c80-ab59-11e9-91a1-3e4432c67aab.png)

![2](https://user-images.githubusercontent.com/18158351/61587501-61a2a980-ab59-11e9-8605-ebe0c9162fb6.png)

**Setup**
 - OS: Arch Linux
 - Version: 1.3.1
 - Smod Version: 3.5.0

**Comment by KarlOfDuty** [comment]
It works for me without issue on 3.4.1, could you test in that version just so I know if it's an smod or scpdiscord issue?

**Comment by Cyanox62** [comment]
On my Windows PC running Smod 3.4.1 they still return the same file path regardless of the parameter.

**Comment by KarlOfDuty** [comment]
Very strange, that returns the local one for me.

In any case, as you have investigated yourself above this does appear to be an smod issue as the function above is returning the wrong path. Could you repost this issue over on the smod repo instead?

**Comment by KarlOfDuty** [comment]
Actually, check your MA config, I think there is a config option there to force the server to only use the global folder, might be you have that on.
