### ISSUE TITLE
Integration/Piping with other Plugins

### ISSUE THREAD

**Issue by PatPeter** [ServerMod/SCPDiscord#205]
**Describe what you want to be implemented**
My plugin, [Friendly Fire Autoban](https://github.com/PatPeter/FriendlyFireAutoban), allows players to type .forgive in the player console. If a player is forgiven for a teamkill, my moderators need to be able to know if that teamkill was forgiven so that they don't have to investigate that.

Are there any PipeEvents or PipeMethods in SCPDiscord for me to implement?

**Motivate why this change is needed/appreciated by the community**
My plugin is used by many Russian servers in addition to my own, but above all that, it would be great if plugins could inject custom events into SCPDiscord.

I looked through the wiki and couldn't find anything on this. If it's possible please let me know.

**Comment by KarlOfDuty** [comment]
Yes there are, check this function if you want to re-use a channel defined in the scpdiscord config: https://github.com/KarlOfDuty/SCPDiscord/blob/21ede153f1598d303ac7800fb87dd434c8f28ae1/SCPDiscordPlugin/SCPDiscord.cs#L248 Otherwise check this function if you want to enter a channel id yourself: https://github.com/KarlOfDuty/SCPDiscord/blob/21ede153f1598d303ac7800fb87dd434c8f28ae1/SCPDiscordPlugin/SCPDiscord.cs#L261

**Comment by KarlOfDuty** [comment]
I don't really know if the piping functions work though as they were broken in smod back when I added them to the plugin.

**Comment by KarlOfDuty** [comment]
Oh, and they always return true, apparently returning void broke the piping.

**Comment by PatPeter** [comment]
I've been meaning to create an issue on ServerMod2 about how piping is broken, specifically PipeEvents which are implemented in the inverse of how they should be (which is that the host plugin triggers the custom event, and the event definition captures the event and executes custom code).

**Comment by KarlOfDuty** [comment]
Yeah, I don't really have any idea what's up with any of the piping things.

**Comment by KarlOfDuty** [comment]
Anyways, closing this as it seems answered.
