### ISSUE TITLE
Our project hacked via the logger for your plugin

### ISSUE THREAD

**Issue by danya201272** [ServerMod/SCPDiscord#207]
He began to write on our server advertising through the logger and so on all projects under your plugin.About the vulnerability told all the people on your server discord multiadmin iRebbok#2429

**Comment by KarlOfDuty** [comment]
Did you have the bot's port open to the internet or did you post your bot token somewhere?

**Comment by danya201272** [comment]
Yes port is open 8888 and 8889

**Comment by danya201272** [comment]
And token i save

**Comment by danya201272** [comment]
Dont show

**Comment by KarlOfDuty** [comment]
Well, yeah don't do that then. If you open the port to the internet anyone can connect to the bot. This is pretty clearly stated in the setup guide.
