### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by danya201272** [ServerMod/SCPDiscord#210]
How setting commands for owner server discord?

**Comment by joker-119** [comment]
![image](https://user-images.githubusercontent.com/10914157/66069986-4ebb3680-e505-11e9-88d9-5b100cd519f4.png)
It took me 15sec to find that.
Cmon.. Read the wiki.

**Comment by danya201272** [comment]
No for 
![image](https://user-images.githubusercontent.com/36302863/66070208-923f9000-e559-11e9-90bf-4ce1982a8d06.png)

**Comment by danya201272** [comment]
I try write Support role id and dont effect

**Comment by joker-119** [comment]
Then you put in the role's ID incorrectly.

It's the ID, not the name.

**Comment by joker-119** [comment]
![image](https://user-images.githubusercontent.com/10914157/66070483-40b9e580-e506-11e9-92a0-15e774bcfc53.png)
like that

**Comment by KarlOfDuty** [comment]
Thanks @galaxy119, if there are any more issues, please state them here.
