### ISSUE TITLE
[BUG] In-game name causes discord mentions

### ISSUE THREAD

**Issue by djakkalap** [ServerMod/SCPDiscord#211]
**Describe the bug**
On the discord server of a SCP:SL server I play on they have a separate channel where teamdamage and other events get logged and displayed.
I noticed that when a user called "@.everyone" (I put a dot there to prevent mentioning some company in Glasgow) did a ton of teamdamage the logs got filled with @.everyone mentions (the bot has admin permissions so everyone actually got mentioned).

**To Reproduce**
To reproduce you need:
- Discord bot that sends player damage event logs in a text channel
- Player called "@.everyone"
- Have this player throw a grenade in an elevator with his MTF teammates

**Screenshots**
![Logs with @everyone mentions](https://user-images.githubusercontent.com/22028918/66275276-3c375900-e887-11e9-92f7-a0b300025103.PNG)

I'm sorry for the low quality of this issue submission, I hope it can be useful to you.

**Comment by KarlOfDuty** [comment]
Have you edited your language files in any way? they are supposed to be removed automatically.

**Comment by djakkalap** [comment]
FYI: I'm not the owner or moderator on this discord server or scp:sl server, but I can communicate with the people who do manage the server and the bot.

But yes the language files were changed.

**Comment by KarlOfDuty** [comment]
That would be why then, they can use the final-regex entry to replace pings with something else or remove them completely.
