### ISSUE TITLE
[BUG] not starting plugin

### ISSUE THREAD

**Issue by Ustaz1505** [ServerMod/SCPDiscord#215]
when i starting a server it gives me err

**To Reproduce**
1. Start server
2. wait for plugins
3. See err
**Screenshots**
![image](https://user-images.githubusercontent.com/56801216/97091272-66e78180-1643-11eb-82cf-bee72c81cbbf.png)

**Setup (please complete the following information):**
 - OS: ubuntu-16.04-x86_64
 - Version: dont know
 - Smod Version: 3.9.3
 - MultiAdmin version: 3.3.1.0

**Comment by KarlOfDuty** [comment]
Hello, you don't seem to have the json library required.

**Comment by DaNoNeOfficial** [comment]
Please tell me in detail how to run it, because I have the same problem!

**Comment by KarlOfDuty** [comment]
Make sure you have the json lib included in the dependencies, also make sure you have the latest version, the old one didn't have that.

**Comment by 1Slender** [comment]
Здравствуйте, я не понял как убрать эту ошибку.

**Comment by KarlOfDuty** [comment]
yes

**Comment by 1Slender** [comment]
Hello, I didn't understand how to remove this error.

**Comment by KarlOfDuty** [comment]
You have to have the dependencies properly installed.
