### ISSUE TITLE
Add Icon to bot

### ISSUE THREAD

**Issue by ITeMbI4** [ServerMod/SCPDiscord#229]
Add Icon to SCPDiscordBot.exe
Maybe this one:
![SCP Foundation Logo](https://user-images.githubusercontent.com/46756889/119263998-a11cff80-bbe1-11eb-9bac-3dd90b7bdc35.png)

**Comment by KarlOfDuty** [comment]
I have added the icon but it seems like application icons are not well supported and only work when building manually via visual studio on desktop. When I try to build on my build server via commandline the icon doesn't get included it seems.
