### ISSUE TITLE
Fix Global/Local Regex

### ISSUE THREAD

**Issue by ITeMbI4** [ServerMod/SCPDiscord#233]
Theare are missed ItemTypes, Classes and Rooms.
Ex.:
![image](https://user-images.githubusercontent.com/46756889/119360262-b7db5900-bcaa-11eb-8f71-32e2cf64337a.png)
There are missed Checkpoint room and there isn't any generator in SCP-173 chamber

**Comment by KarlOfDuty** [comment]
I have updated it now, not sure if the new version creates any issues or conflicts between replacements though.
