### ISSUE TITLE
EXILED version?

### ISSUE THREAD

**Issue by Underlyingglitch** [ServerMod/SCPDiscord#235]
Release 1.4.0 states: "Updated smod version"

Release candidate 2.0.0-rc1 states: "This allows for the plugin to be split into an Exiled and Smod version at some point but the bot staying the same for both."

Is an EXILED version still planned? And if so, when is it expected to be finished?

**Comment by KarlOfDuty** [comment]
It depends on how long the game devs take with their own plugin api, I feel like I'd rather work with that for more api stability.
