### ISSUE TITLE
Re-connecting plugin to bot causes none messages sent to discord server

### ISSUE THREAD

**Issue by REALMWTH** [ServerMod/SCPDiscord#25]

**Comment by KarlOfDuty** [comment]
Do you mean empty messages or that no messages can be sent after that?

**Comment by REALMWTH** [comment]
No messages can be sent after that BUT connection between plugin and bot seems to be ok. Plugin just doesn't generate any messages after that.

**Comment by KarlOfDuty** [comment]
I see, I'll look into this.

**Comment by KarlOfDuty** [comment]
I think I have fixed this for the next version now.

**Comment by REALMWTH** [comment]
Going to test if it's fixed

**Comment by KarlOfDuty** [comment]
Is it?

**Comment by KarlOfDuty** [comment]
Should be fixed with this update. #36
