### ISSUE TITLE
Crash when I start the server with the new version

### ISSUE THREAD

**Issue by Barna13** [ServerMod/SCPDiscord#37]
Ubuntu 16.04
The following assembly referenced from /home/barnaby/Steam/steamapps/common/SCP Secret Laboratory/sm_plugins/dependencies/Newtonsoft.Json.dll could not be loaded:
     Assembly:   System.Xml.Linq    (assemblyref_index=4)
     Version:    3.5.0.0
     Public Key: b77a5c561934e089
The assembly was not found in the Global Assembly Cache, a path listed in the MONO_PATH environment variable, or in the location of the executing assembly (/home/barnaby/Steam/steamapps/common/SCP Secret Laboratory/SCPSL_Data/../sm_plugins/dependencies/).

Could not load file or assembly 'System.Xml.Linq, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
Could not load file or assembly 'System.Xml.Linq, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
The class Newtonsoft.Json.Converters.XObjectWrapper could not be loaded, used in Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
The class Newtonsoft.Json.Converters.XObjectWrapper could not be loaded, used in Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
The class Newtonsoft.Json.Converters.XObjectWrapper could not be loaded, used in Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
The class Newtonsoft.Json.Converters.XObjectWrapper could not be loaded, used in Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
The class Newtonsoft.Json.Converters.XObjectWrapper could not be loaded, used in Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
The class Newtonsoft.Json.Converters.XContainerWrapper could not be loaded, used in Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
The class Newtonsoft.Json.Converters.XObjectWrapper could not be loaded, used in Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
The class Newtonsoft.Json.Converters.XObjectWrapper could not be loaded, used in Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
The class Newtonsoft.Json.Converters.XContainerWrapper could not be loaded, used in Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
The following assembly referenced from /home/barnaby/Steam/steamapps/common/SCP Secret Laboratory/sm_plugins/dependencies/Newtonsoft.Json.dll could not be loaded:
     Assembly:   System.Runtime.Serialization    (assemblyref_index=5)
     Version:    3.0.0.0
     Public Key: b77a5c561934e089
The assembly was not found in the Global Assembly Cache, a path listed in the MONO_PATH environment variable, or in the location of the executing assembly (/home/barnaby/Steam/steamapps/common/SCP Secret Laboratory/SCPSL_Data/../sm_plugi

**Comment by KarlOfDuty** [comment]
Have you updated mono in a while?

**Comment by KarlOfDuty** [comment]
Also, verify that Newtonsoft.Json.dll is located in sm_plugins/dependencies

**Comment by KarlOfDuty** [comment]
Closed for inactivity.
