### ISSUE TITLE
Suggestion for ban command (Discord)

### ISSUE THREAD

**Issue by ArseeniK** [ServerMod/SCPDiscord#40]
Maybe it can be usefull to check for duplicate SteamID ban before banning and check nickname/reason strings (may broke the tokenized file using ";" in reason, or nickname

**Comment by KarlOfDuty** [comment]
I'll check for semicolons but I don't think duplicate steamid checking is necessary at this point.

**Comment by KarlOfDuty** [comment]
Fixed. #44
