### ISSUE TITLE
The bot writes OnHurt messages four times

### ISSUE THREAD

**Issue by Barna13** [ServerMod/SCPDiscord#5]
and the killer/killed is the same like this:
Gaby (76561198046907785) was hurt by Gaby (76561198046907785) using SCP_096.
Gaby (76561198046907785) was hurt by Gaby (76561198046907785) using SCP_096.
Gaby (76561198046907785) was hurt by Gaby (76561198046907785) using SCP_096.
Gaby (76561198046907785) was hurt by Gaby (76561198046907785) using SCP_096.
Gaby (76561198046907785) was hurt by Gaby (76561198046907785) using SCP_096.

**Comment by KarlOfDuty** [comment]
Is this specifically for SCP-096 or have you noticed it for anything else too?

I think the issue is an error with the event that is thrown when 096 kills someone in that case and I'll contact the smod devs about that.

**Comment by Barna13** [comment]
On my server its for all the role on On hurt(i'm gonna disabled event onhurt)
The supersun warrior (76561198214248505) was hurt by Ralph44B (76561198421023463) using E11_STANDARD_RIFLE.
The supersun warrior (76561198214248505) was hurt by Ralph44B (76561198421023463) using E11_STANDARD_RIFLE.
The supersun warrior (76561198214248505) was hurt by Ralph44B (76561198421023463) using E11_STANDARD_RIFLE.
The supersun warrior (76561198214248505) was hurt by Ralph44B (76561198421023463) using E11_STANDARD_RIFLE.
The supersun warrior (76561198214248505) was hurt by Ralph44B (76561198421023463) using E11_STANDARD_RIFLE.

**Comment by KarlOfDuty** [comment]
Yes, I also disabled that on my server. But I know for a fact the normal human weapons only send once per shot, at least they do on my server.

**Comment by KarlOfDuty** [comment]
I'll have a look at this later today and see what I can find, the issue is that I only have myself to test with so most events go unnoticed until actually in use.

**Comment by KarlOfDuty** [comment]
I've tested it and it seems to be fixed now. Otherwise it is on ServerMod's end.
