### ISSUE TITLE
NONE and UNASSIGNED event spam

### ISSUE THREAD

**Issue by Barna13** [ServerMod/SCPDiscord#51]
onplayerdie self seem bug with scp "playername" killed themselves using SCP-173 or SCP-096...
EDIT: onplayerdie for SCP-173 and SCP-096 it's smod or game problem not scpdiscord sorry
I have a second problem when I make the command +ban steamid timeandunit the plugin say :
Plugin connection lost.
Plugin connection lost.
Plugin connection lost.

sometime the plugin spam UNASSIGNED or NONE

**Comment by KarlOfDuty** [comment]
The first is an smod issue I can't do anything about, I'll have a look at the others.

**Comment by KarlOfDuty** [comment]
I am working on fixing commands now, they already work in your version it's just the feedback that causes a disconnect right after for some reason.

**Comment by KarlOfDuty** [comment]
What do you mean by it spamming unassigned or none, can you post a screenshot?

**Comment by KarlOfDuty** [comment]
Moved to right ticket:

It's in french but it's the same things
NONE kill himself with none. (i think its self event)
NONE s'est suicidé avec NONE.
est devenu un UNASSIGNED.
NONE s'est suicidé avec NONE.
est devenu un UNASSIGNED.
NONE s'est suicidé avec NONE.
est devenu un UNASSIGNED.
NONE s'est suicidé avec NONE.
est devenu un UNASSIGNED.
NONE s'est suicidé avec NONE.
est devenu un UNASSIGNED.
NONE s'est suicidé avec NONE.
est devenu un UNASSIGNED.
NONE s'est suicidé avec NONE.
est devenu un UNASSIGNED.
Teuffa (76561198367107276) a jeté Grenade incapacitante.
NONE s'est suicidé avec NONE.
est devenu un UNASSIGNED.
NONE s'est suicidé avec NONE.
est devenu un UNASSIGNED.

**Comment by KarlOfDuty** [comment]
It would seem another plugin is causing this, default smod does not call this event for no reason like this.

**Comment by KarlOfDuty** [comment]
Fixed. #60
