### ISSUE TITLE
Memory leak ?

### ISSUE THREAD

**Issue by Barna13** [ServerMod/SCPDiscord#52]
i have this error on my screen with scpdiscord, i'm on ubuntu 16.04 6gb of ram (96% used by the bot)
(node:11287) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by KarlOfDuty** [comment]
Very strange, I don't have the same issue on the same OS. I'll try to find the issue, did you use any discord commands btw?

**Comment by Barna13** [comment]
maybe +ban command

**Comment by KarlOfDuty** [comment]
Ok, I know the discord commands have some issue with them right now that may be causing some memory leaks, I'll have a look.

**Comment by KarlOfDuty** [comment]
I can't really get it to cause this memory leak, I've had four bots on the whole day and none of them use more than 150mb of memory.

**Comment by Barna13** [comment]
idk if it's a 100% scpdiscord because now when I look "top" i seen any proces with 100% mem usage but he have one

**Comment by KarlOfDuty** [comment]
Could you post a screenshot of htop sorted by memory? (F6) I'd prefer htop over top.

**Comment by Barna13** [comment]
I will make it when it reappears

**Comment by Barna13** [comment]
It's in french but it's the same things
NONE  kill himself with none. (i think its self event)
NONE  s'est suicidé avec NONE.
 est devenu un UNASSIGNED.
NONE  s'est suicidé avec NONE.
 est devenu un UNASSIGNED.
NONE  s'est suicidé avec NONE.
 est devenu un UNASSIGNED.
NONE  s'est suicidé avec NONE.
 est devenu un UNASSIGNED.
NONE  s'est suicidé avec NONE.
 est devenu un UNASSIGNED.
NONE  s'est suicidé avec NONE.
 est devenu un UNASSIGNED.
NONE  s'est suicidé avec NONE.
 est devenu un UNASSIGNED.
Teuffa (76561198367107276) a jeté Grenade incapacitante.
NONE  s'est suicidé avec NONE.
 est devenu un UNASSIGNED.
NONE  s'est suicidé avec NONE.
 est devenu un UNASSIGNED.

**Comment by Barna13** [comment]
I have see an another problem. I have 4 servers in the same machine and the 4 servers in same bot, the status say something like 17/68 but i have 80 slots in the total and few seconds after the statuts disappears and the bot is absent (orange icon on discord) and few seconds after the bot is online (green on discord) and the status does not reappear.

**Comment by KarlOfDuty** [comment]
Oh yeah, forgot about people with several servers per bot.

**Comment by KarlOfDuty** [comment]
Could you provide a screenshot of the original issue here?

**Comment by Barna13** [comment]
i have few problem with my servers now, when my severs restart i will send you a image

**Comment by Barna13** [comment]
https://gyazo.com/903d250143c992e1f9faab2a5111f1af

**Comment by KarlOfDuty** [comment]
![image](https://user-images.githubusercontent.com/18099825/44432774-b9c8d880-a5a3-11e8-810b-a298063cd452.png)

**Comment by Barna13** [comment]
I just found the memory problem this comes from the scpl server and not the bot discord

**Comment by KarlOfDuty** [comment]
That makes more sense. The SCP:SL servers have big memory leaks. I recommend using MultiAdmin if you aren't, it fixes the biggest ones.
