### ISSUE TITLE
Create a better way to keep languages up to date

### ISSUE THREAD

**Issue by REALMWTH** [ServerMod/SCPDiscord#77]
It happens even if files are already in language folder within config folder.

**Comment by KarlOfDuty** [comment]
Could you post a screenshot of the console and your languages folder?

**Comment by REALMWTH** [comment]
https://imgur.com/a/BT56z6b

**Comment by REALMWTH** [comment]
So if I manually change translation in language folder, it is getting reverted back EVERY restart

**Comment by KarlOfDuty** [comment]
Right, that is how the plugin is supposed to work to make sure the newest version of the language is always available for the user. I can see how that is a problem for translators. I recommend that you rename the file to russian2 and then set russian2 as your language in the config.

**Comment by KarlOfDuty** [comment]
I'll see if I can figure out a better system.

**Comment by KarlOfDuty** [comment]
Done. d07d326733d63e3ac0851047405c6187479ad63b
