### ISSUE TITLE
Remove player object from 914changeknob event

### ISSUE THREAD

**Issue by REALMWTH** [ServerMod/SCPDiscord#78]
Instead it sends this:

> UNCONNECTED (----------------------------------------)

**Comment by REALMWTH** [comment]
Also input items are outputted like:
`UnityEngine.Collider[]`

**Comment by KarlOfDuty** [comment]
Interesting, the input items thing is going to be removed in the next update. But I think the unconnected player/steamid thing was just a coincidence, all commands seem to send that from time to time.

**Comment by KarlOfDuty** [comment]
whoops, didn't mean to click that

**Comment by REALMWTH** [comment]
But in THIS case it is being send as UNCONNECTED with 100% probability

**Comment by KarlOfDuty** [comment]
Ok, I will have a look at it.

**Comment by KarlOfDuty** [comment]
This was fixed in ServerMod 3.1.16.
