### ISSUE TITLE
Bug: offline unban doesn't delete record in ipbans.txt

### ISSUE THREAD

**Issue by REALMWTH** [ServerMod/SCPDiscord#89]

**Comment by KarlOfDuty** [comment]
Hm, this should work but I'll have a look.

**Comment by KarlOfDuty** [comment]
![image](https://user-images.githubusercontent.com/18099825/45836438-29e68d80-bd0d-11e8-8c72-2ed1487bbd84.png)

![image](https://user-images.githubusercontent.com/18099825/45836453-34088c00-bd0d-11e8-9387-bfa951057a61.png)

![image](https://user-images.githubusercontent.com/18099825/45836469-3b2f9a00-bd0d-11e8-8e46-15787340c1dd.png)

Works for me

**Comment by REALMWTH** [comment]
It is not working if I unban by SteamID

**Comment by KarlOfDuty** [comment]
Well no, you enter the one you wish to remove. There is nothing in the ban file that ties the ip to the steamid so there is no was to know the ip from the steamid.

**Comment by REALMWTH** [comment]
But why we can't find username of user we want to unban in steamid ban list and then find the same user by nickname in ip ban list, then remove?

**Comment by KarlOfDuty** [comment]
That would absolutely be possible, but consider this: A server could have a rule against impersonating others like mine does, so it would be very likely that there would be many people with the same name in the ban lists and then it would unban all of them.

**Comment by REALMWTH** [comment]
This is absolutely true and there is no way of checking for correct ban. I will suggest development team to add smth like BANID variable before the actual ban info.

**Comment by KarlOfDuty** [comment]
Yes, that sounds like a good idea. Although I did just realise that they may both have the exact same time stamp, so I'll look into if I could match them that way.
