### ISSUE TITLE
NodeJS bot uses ~10% CPU time without any reason

### ISSUE THREAD

**Issue by REALMWTH** [ServerMod/SCPDiscord#90]

**Comment by KarlOfDuty** [comment]
This issue is under investigation, I'm still only dedicating very little time to this as I have a lot to do in school atm. So it may take some time.

**Comment by KarlOfDuty** [comment]
0.3.4 may have better performance in this regard.

**Comment by KarlOfDuty** [comment]
I will keep trying to improve the cpu performance but there is no specific part that is using way more than it should currently. I'll close this as it isn't really about a specific problem.
