### ISSUE TITLE
Define damage type config line for OnHurt event

### ISSUE THREAD

**Issue by REALMWTH** [ServerMod/SCPDiscord#91]

**Comment by KarlOfDuty** [comment]
What do you mean exactly?

**Comment by REALMWTH** [comment]
I don't want some damage types being sended to Discord, such as: POCKETDIMENSION or SERVER

**Comment by KarlOfDuty** [comment]
You can use the regex lines to delete any messages you don't want to see. `".*HELLO.*":""` will delete all messages containing HELLO.

**Comment by KarlOfDuty** [comment]
Although I guess this also calls for rewriting my language file system so it's possible to just edit the files instead of making a personal copy of them.

**Comment by REALMWTH** [comment]
Thanks! However, I will look into adding config line and change OnHurt event so I can make it more user-friendly.

**Comment by KarlOfDuty** [comment]
I think that'd be for a fork because I don't see how that would work without adding like 200 config lines for every single thing one could want to filter.

**Comment by KarlOfDuty** [comment]
Anyway here is an improvement for you in the next plugin version #93
