### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by REALMWTH** [ServerMod/SCPDiscord#92]
> (node:4428) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
>     at TLSWrap.onread (net.js:622:25)
> (node:4428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:4428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:4428) UnhandledPromiseRejectionWarning: Error: socket hang up
>     at TLSSocket.onHangUp (_tls_wrap.js:1148:19)
>     at Object.onceWrapper (events.js:313:30)
>     at emitNone (events.js:111:20)
>     at TLSSocket.emit (events.js:208:7)
>     at endReadableNT (_stream_readable.js:1064:12)
>     at _combinedTickCallback (internal/process/next_tick.js:139:11)
>     at process._tickCallback (internal/process/next_tick.js:181:9)
> (node:4428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by KarlOfDuty** [comment]
Very strange, I already check for this type of error. This error doesn't say anything about where it occurred, do you know what happened when the error occurred?

**Comment by REALMWTH** [comment]
This seems to be a problem with OVH hosting's DDoS protection / firewall rules, however firewall disable doesn't fix issue. Need more info about which ports does js bot use and to which IP it connects.
I didn't have such error when used another hosting.

**Comment by KarlOfDuty** [comment]
You set which port and IP the bot uses in the plugin and bot configs.

**Comment by REALMWTH** [comment]
Is this the outbound port for connection between discord bot and discord master server?

**Comment by KarlOfDuty** [comment]
Ah, no it is not, I think it just uses the normal http/https ports 80 and 443.

**Comment by REALMWTH** [comment]
However, adding these ports to exceptions fixed issue.

**Comment by KarlOfDuty** [comment]
Nice! I never had this issue as I already have those ports open on my server for running my website.
